9-13. Dice (Alexa)
codingfriendsfun/pcc pull request #15
Opened 2024-02-29 06:47 UTC by Bookwormlex

2024-02-29 06:47 UTC, pep8speaks commented
Hello @Bookwormlex! Thanks for opening this PR. 

* In the file [`chapter_09/9-13.py`](https://github.com/codingfriendsfun/pcc/blob/a7bf84833b9669c4195ba9100a02f6aa566a9808/chapter_09/9-13.py):

> [Line 5:1](https://github.com/codingfriendsfun/pcc/blob/a7bf84833b9669c4195ba9100a02f6aa566a9808/chapter_09/9-13.py#L5): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 26:1](https://github.com/codingfriendsfun/pcc/blob/a7bf84833b9669c4195ba9100a02f6aa566a9808/chapter_09/9-13.py#L26): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 26:1](https://github.com/codingfriendsfun/pcc/blob/a7bf84833b9669c4195ba9100a02f6aa566a9808/chapter_09/9-13.py#L26): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2024-04-01 02:55 UTC, therawv requested changes
You didn't create a 6 sided die and roll it ten times. The code looks correct besides the fact.

2024-04-07 20:43 UTC, Bookwormlex commented
Fixed!

2024-04-07 21:36 UTC, therawv approved these changes
looks good

2024-04-13 18:55 UTC, merged