Eng/pr noelle 10 8
codingfriendsfun/pcc pull request #45
Opened 2024-04-07 20:49 UTC by Kerowyn202

2024-04-07 20:49 UTC, pep8speaks commented
Hello @Kerowyn202! Thanks for opening this PR. 

* In the file [`chapter_10/10-8.py`](https://github.com/codingfriendsfun/pcc/blob/34d9299357586f67eb8ea9fb8183165967098981/chapter_10/10-8.py):

> [Line 9:1](https://github.com/codingfriendsfun/pcc/blob/34d9299357586f67eb8ea9fb8183165967098981/chapter_10/10-8.py#L9): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 14:1](https://github.com/codingfriendsfun/pcc/blob/34d9299357586f67eb8ea9fb8183165967098981/chapter_10/10-8.py#L14): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 14:1](https://github.com/codingfriendsfun/pcc/blob/34d9299357586f67eb8ea9fb8183165967098981/chapter_10/10-8.py#L14): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2024-04-13 20:01 UTC, therawv reviewed
I'm not really familiar with how you set up the paths and when I tried to execute the code it didn't run properly. I've been using relative paths from the same directory. Maybe you should adjust it?

2024-04-14 00:09 UTC, Kerowyn202 commented
Weird, it runs properly on my computer, both when I have the FileNotFound exception set up to trigger and when I don't. What error are you getting @therawv ?

2024-04-17 01:24 UTC, therawv requested changes
I reviewed this again today and its failing to run properly. It's failing to find the cat.txt and dog.txt files I posted a screenshot in the discord for further context.

2024-04-17 19:37 UTC, Kerowyn202 commented
Edited it to include specifications about where the program should be run in the error message. So you'll get the custom error if you 1) don't have the files or 2) don't run it from PCC and run it from any other folder

2024-04-18 00:59 UTC, therawv commented on chapter_10/10-8.py
> +pet_names = ['./chapter_10/cats.txt', './chapter_10/dogs.txt']
Your code would be more robust if you used a relative path to the tune of
pet_names = ['cats.txt', 'dogs.txt']

Or if you anchored the path, to the tune of what Alexa did in her chapter 10-12 (this wouldn't be the exact code but it's an example of how she roots her directory)

import json
import os
from pathlib import Path

def getRootDir():
    """ """
    # deal with "What folder am I working from?"
    cwd = os.getcwd()
    index = cwd.find("chapter")
    if index > 0:
        cwd = cwd[:index]
    # else do nothing, assume we're in workspace root
    return cwd

def main():
    """ """
    rootDir = getRootDir()

    # create scratch dir
    scratchDir = Path(f"{rootDir}/scratch_files")
    if not scratchDir.exists():
        os.mkdir(scratchDir.resolve())

This change still leaves lots of potential failure cases when a user pulls the code(I'm still getting an error where I shouldn't, and I am in the PCC directory but its not in the same base location as you). At the very least you should comment the required filepath/placement somewhere in here so a developer would know how to set it up.

2024-04-18 01:00 UTC, therawv reviewed
This change doesn't really address the cause of the code failing in the first place. There are simpler solutions to a more robust answer.

2024-05-06 04:11 UTC, therawv approved these changes

2024-05-07 18:12 UTC, merged